/**
 * @dashtop/widget-sdk
 *
 * SDK for building Dashtop dashboard widgets.
 *
 * Widget developers use this to:
 * 1. Define their widget with proper types
 * 2. Use the bridge to communicate with the host dashboard
 * 3. Build with the Vite plugin for correct output format
 * 4. Package as .dashtop with the CLI
 */

// ── Widget Types ──────────────────────────────

/**
 * Props passed to every widget's render function.
 */
export interface WidgetRenderProps<
  TConfig = Record<string, unknown>,
> {
  /** The merged configuration (defaults + user overrides) */
  config: TConfig;
  /** Whether the dashboard is in edit mode */
  isEditing: boolean;
  /** Call this to update the widget's configuration */
  onConfigChange: (patch: Partial<TConfig>) => void;
}

/**
 * A widget's render function. This is the default export of a widget bundle.
 * It receives a root DOM element and props, and is responsible for rendering.
 */
export type WidgetRenderFn<TConfig = Record<string, unknown>> = (
  root: HTMLElement,
  props: WidgetRenderProps<TConfig>
) => void | (() => void);

/**
 * Widget manifest — describes the widget for the marketplace.
 * This is included in manifest.json of the .dashtop package.
 */
export interface WidgetManifest {
  /** Unique widget type identifier */
  widgetType: string;
  /** Display name */
  name: string;
  /** Short description (max 200 chars) */
  description: string;
  /** Category for marketplace filtering */
  category:
    | "ai"
    | "analytics"
    | "media"
    | "productivity"
    | "data-viz"
    | "utility"
    | "communication";
  /** Tags for search/discovery (max 10) */
  tags: string[];
  /** Semver version */
  version: string;
  /** Default widget configuration */
  defaultConfig: Record<string, unknown>;
  /** Default grid size (columns x rows, out of 12-column grid) */
  defaultSize: { w: number; h: number };
  /** Minimum grid size */
  minSize: { w: number; h: number };
  /** Maximum grid size (optional) */
  maxSize?: { w: number; h: number };
  /** Required permissions */
  permissions?: WidgetPermission[];
  /**
   * JSON Schema for the settings form.
   * The host dashboard auto-generates a settings UI from this schema.
   * This runs in the TRUSTED parent frame, not in the widget iframe.
   */
  settingsSchema?: Record<string, unknown>;
}

/** Available permissions a widget can request */
export type WidgetPermission =
  | "network:fetch"
  | "storage:local"
  | "clipboard:read"
  | "clipboard:write"
  | "theme:read"
  | "resize:request";

// ── Dashtop Package Manifest ──────────────────

/**
 * Full .dashtop package manifest.
 * Generated by `dashtop-widget pack` command.
 */
export interface DashtopPackageManifest {
  id: string;
  name: string;
  version: string;
  description: string;
  type: "widget";
  category: string;
  tags: string[];
  author: {
    name: string;
    username: string;
  };
  dashtopVersion: string;
  widget: {
    widgetType: string;
    entrypoint: string;
    sandbox: true;
    permissions: string[];
    defaultConfig: Record<string, unknown>;
    defaultSize: { w: number; h: number };
    minSize: { w: number; h: number };
    maxSize?: { w: number; h: number };
    settingsSchema?: Record<string, unknown>;
  };
}

// ── Helper: Define Widget ─────────────────────

/**
 * Helper to define a widget with proper typing.
 *
 * @example
 * ```ts
 * import { defineWidget } from '@dashtop/widget-sdk';
 *
 * interface MyConfig {
 *   color: string;
 *   label: string;
 * }
 *
 * export default defineWidget<MyConfig>((root, { config, onConfigChange }) => {
 *   root.innerHTML = `<div style="color: ${config.color}">${config.label}</div>`;
 *
 *   root.querySelector('div')?.addEventListener('click', () => {
 *     onConfigChange({ label: 'Clicked!' });
 *   });
 *
 *   // Optional: return cleanup function
 *   return () => { root.innerHTML = ''; };
 * });
 * ```
 */
export function defineWidget<TConfig = Record<string, unknown>>(
  render: WidgetRenderFn<TConfig>
): WidgetRenderFn<TConfig> {
  return render;
}

// Re-export bridge for convenience
export { initBridge } from "./bridge";
